### ISSUE TITLE
Support sitepackages 

### ISSUE THREAD

**Issue by koodzi** [tox-dev/tox-uv#109]
## Issue

When I run tox test with `sitepackages = true` it seems it does not see installed packages.

## Environment

- OS: Ubuntu /Docker 

## Output of running tox

```
/root/.local/share/uv/tools/tox/bin/uv venv -p /root/.local/share/uv/tools/tox/bin/python --allow-existing -v /gcl-builds/.tox/pytorch
```

https://github.com/tox-dev/tox-uv/blob/main/src/tox_uv/_venv.py#L196 I don't see uv venv's `--system-site-packages`. But I maybe it is done different way?

**Comment by gaborbernat** [comment]
Yeah we don't support this yet, but PR welcome.
