### ISSUE TITLE
hangs when installing local package

### ISSUE THREAD

**Issue by davidszotten** [tox-dev/tox-uv#11]
hi. very excited to try this out, thanks!

tox seems to hang when installing the local package

```
# cat pyproject.toml
[tool.poetry]
name = "my-package"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`tox` seems to hang at

```
py: 255 W install_package> /.venv/bin/uv pip install --reinstall --no-deps my_package@/tmp/my-package/.tox/.tmp/package/6/my_package-0.1.0.tar.gz [tox/tox_env/api.py:427]
Resolved 1 package in 231ms
Building my-package @ file:///tmp/my-package/.tox/.tmp/package/6/my_package-0.1.0.tar.gz
░░░░░░░░░░░░░░░░░░░░ [0/1] Fetching packages...
```

if i pause the execution and run the `uv` command manually that works fine

```
#  /.venv/bin/uv pip install --reinstall --no-deps my_package@/tmp/my-package/.tox/.tmp/package/6/my_package-0.1.0.tar.gz
Resolved 1 package in 4ms
   Built my-package @ file:///tmp/my-package/.tox/.tmp/package/6/my_package-0.1.0.tar.gz Downloaded 1 package in 303ms
Installed 1 package in 0ms
 - my-package==0.1.0 (from file:///tmp/my-package/.tox/.tmp/package/1/my_package-0.1.0.tar.gz)
 + my-package==0.1.0 (from file:///tmp/my-package/.tox/.tmp/package/6/my_package-0.1.0.tar.gz)
```

any advice on how to continue debugging this?

```
tox==4.13.0
tox-uv==1.2.0
```

```
uv 0.1.3
```

**Comment by gaborbernat** [comment]
Sounds like a bug in uv, can you open issue upstream?

**Comment by davidszotten** [comment]
even though it works fine when pausing tox and calling uv directly? i can't reproduce without tox

**Comment by gaborbernat** [comment]
Even though l, I gather it is because we call it via setting the environment variable, which should be valid. Also what's hanging is uv, not tox here.

**Comment by davidszotten** [comment]
> what's hanging is uv, not tox here

yes that's fair. will raise there

> we call it via setting the environment variable

could you elaborate? i don't quite follow sorry (might help me with debugging/reporting)

**Comment by gaborbernat** [comment]
See https://github.com/tox-dev/tox-uv/blob/main/src%2Ftox_uv%2F_venv.py#L102, we don't change the current working directory.

**Comment by gaborbernat** [comment]
You can try package=wheel, perhaps that will work around for the time being 🤔

**Comment by zanieb** [comment]
I'm a little confused, not changing the working directory to the virtual environment is causing us to hang?

**Comment by gaborbernat** [comment]
I'm not saying that was causing it, but it is a difference compared to the manual run the reporter did here. So just something to consider when trying to reproduce it.

**Comment by gaborbernat** [comment]
Can you please update the run output with https://github.com/tox-dev/tox-uv/releases/tag/1.3.0 using `tox -rvvv`. Thanks!

**Comment by davidszotten** [comment]
apologies. i raised a bug with uv, they fixed it and i closed the issue, but forgot to circle back here.

**Comment by gaborbernat** [comment]
@davidszotten can you link the upstream report please?

**Comment by davidszotten** [comment]
https://github.com/astral-sh/uv/issues/1588

i linked in the other direction and was expecting one of those github auto-backlinks "this was referenced ...". not sure why one wasn't added
