### ISSUE TITLE
add `uv_sync_groups` and `uv_sync_only_groups`

### ISSUE THREAD

**Issue by resulal** [tox-dev/tox-uv#113]
## What's the problem this feature will solve?

When using [`uv-venv-lock-runner`](https://github.com/tox-dev/tox-uv?tab=readme-ov-file#tox-environment-types-provided) with a `uv.lock` file, there is no option to specify the new [`dependency-groups`](https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups), except [`with_dev`](https://github.com/tox-dev/tox-uv?tab=readme-ov-file#with_dev) boolean.

`uv` has already implemented `--group` and `--only-group` options to [`uv sync`](https://docs.astral.sh/uv/reference/cli/#uv-sync), where the latter also omits the project itself. Both options can be called multiple times. 

## Describe the solution you'd like

Similar to [`uv_sync_flags`](https://github.com/tox-dev/tox-uv?tab=readme-ov-file#uv_sync_flags) and [`extras`](https://github.com/tox-dev/tox-uv?tab=readme-ov-file#extras), one can imagine specifying the `dependency-groups` as:
```md
uv_sync_only_groups = 
  docs
```
where the following table exists in `pyproject.toml` file.
```
[dependency-groups]
docs = [
  "mkdocs>=1.6.0",
]
```
This way the `uv.lock` file can be used across multiple target `tox run` environments with the fast `uv-venv-lock-runner` runner.

**Comment by gaborbernat** [comment]
You can patch those flags directly via the configuration you mentioned. We don't actually need to expose it at a separate configuration.
