### ISSUE TITLE
No Python 3.None In `PATH` for pypy3 environment

### ISSUE THREAD

**Issue by pmbarrett314** [tox-dev/tox-uv#14]
I have a tox environment for pypy3. I installed tox-uv, and everything seems to be working except that one environment. It tries to run the following command

pypy3: venv> /Users/paul/Library/Caches/pypoetry/virtualenvs/curses-menu-7NMq2ySU-py3.10/bin/uv venv -p 3.None /Users/paul/code/projects/curses-menu/.tox/pypy3/.venv

and prints the following error

× No Python 3.None In `PATH`. Is Python 3.None installed?

**Comment by gaborbernat** [comment]
Yeah, we don't support pypy yet 😅PR to add support is welcomed 😎

**Comment by pmbarrett314** [comment]
Thanks for the reply! Good to know. Can I disable tox-uv for specific Tox environments in the meantime?

**Comment by gaborbernat** [comment]
You can see the runner to the default in tox. See readme.

**Comment by pmbarrett314** [comment]
I ended up needing to set a non-default package_env as well

```
[testenv:pypy3]
package_env=.pkg_pypy
runner=virtualenv
```

**Comment by gaborbernat** [comment]
I think 1.3.0 will fix this.
