### ISSUE TITLE
Tox env is no longer recognized by IDE

### ISSUE THREAD

**Issue by AntoineD** [tox-dev/tox-uv#30]
## What's the problem this feature will solve?

IDE (probably other tools too) that are configured to point to a python executable as for instance `.tox/py311/bin/python`, need to be changed to `.tox/py311/.venv/bin/python`,

## Describe the solution you'd like

Prevent this change by installing the env in the same location as the original tox?

**Comment by gaborbernat** [comment]
uv doesn't allow other files to exist in the venv, so we can't do this.

**Comment by AntoineD** [comment]
I do not get it, which other files?

**Comment by gaborbernat** [comment]
```
❯ ls .tox/dev -alth
total 12K
drwxr-xr-x 13 bgabor8 staff  416 Mar  6 09:24 ../
drwxr-xr-x  6 bgabor8 staff  192 Mar  5 14:29 log/
drwxr-xr-x 72 bgabor8 staff 2.3K Mar  5 14:29 bin/
-rw-r--r--  1 bgabor8 staff 1.8K Mar  5 14:29 .tox-info.json
drwxr-xr-x  9 bgabor8 staff  288 Mar  5 14:23 ./
-rw-r--r--  1 bgabor8 staff  342 Mar  5 14:22 pyvenv.cfg
-rw-r--r--  1 bgabor8 staff   40 Mar  5 14:22 .gitignore
drwxr-xr-x  3 bgabor8 staff   96 Mar  5 14:22 lib/
drwxr-xr-x  2 bgabor8 staff   64 Mar  5 14:22 tmp/
```

.gitignore, log, tmp,  .tox-info.json.

**Comment by gaborbernat** [comment]
> Do you mean when a pre-existing env was created with virtualenv?
> 
> If yes, why not remove it?

No that's not what I meant. These additional files are not related to virtualenv. These are files and folders generated by tox itself and are required for its functioning.

**Comment by AntoineD** [comment]
This is clear now, thank you.

**Comment by AntoineD** [comment]
It seems the current version of `tox-uv` now installs the environment at the same location as `tox`, is it expected?

**Comment by gaborbernat** [comment]
YeS.
