### ISSUE TITLE
Installation fails if the package contains '-'

### ISSUE THREAD

**Issue by hkad98** [tox-dev/tox-uv#31]
## Issue

The installation fails when the package contains a '-' character in the name. The following line of code causes it:

https://github.com/tox-dev/tox-uv/blob/main/src/tox_uv/_installer.py#L88

The error message I got: 

Caused by: Package metadata name `gooddata-sdk` does not match given name `gooddata`

## Environment

Provide at least:

- OS: 14.2 (23C64)

<details open>
<summary>Output of <code>pip list</code> of the host Python, where <code>tox</code> is installed</summary>

```console
Package             Version
------------------- -------
cachetools          5.3.3
chardet             5.2.0
colorama            0.4.6
distlib             0.3.8
filelock            3.13.1
gooddata-api-client 1.14.0
gooddata-dbt        1.14.0
gooddata-pandas     1.14.0
gooddata-sdk        1.14.0
packaging           23.2
pip                 24.0
platformdirs        4.2.0
pluggy              1.4.0
pyproject-api       1.6.1
setuptools          69.1.1
tox                 4.14.0
tox-uv              1.5.0
uv                  0.1.15
virtualenv          20.25.1
```

</details>

**Comment by gaborbernat** [comment]
PR welcome 😊

**Comment by gaborbernat** [comment]
Can you please provide the full output of your error?  Now I think your build backend is generating an invalid wheel file name, so is a bug there - see https://peps.python.org/pep-0427/#escaping-and-unicode

**Comment by hkad98** [comment]
I tried the new version – 1.5.1, and it works now. Thank you for the fix.
