### ISSUE TITLE
`uv pip freeze` exists

### ISSUE THREAD

**Issue by hauntsaninja** [tox-dev/tox-uv#4]
I think `uv`'s initial version shipped with this (it was only missing `pip list`). Just mentioning since the README says:

> Also, uv does not have at the moment a pip freeze/list like feature, so we still install pip into the environment to perform this operation via pip.

**Comment by gaborbernat** [comment]
Ah, a good improvement opportunity 👍

**Comment by gaborbernat** [comment]
Done via #5
