### ISSUE TITLE
Let uv provide python versions

### ISSUE THREAD

**Issue by bluss** [tox-dev/tox-uv#72]
## What's the problem this feature will solve?

Hi, do you plan to let Uv supply python installations? It could install all necessary versions.
Similar to the experiment I did with rye ( https://github.com/bluss/tox-rye ).

It removes the need for python installs to be arranged up front. Or enables already installed but not previously discovered (by tox) python versions installed by uv.

## Describe the solution you'd like

tox-uv would request (and if needed install) each python version from Uv. Uv has a preview feature for installing python (`uv python`).

## Alternative Solutions

Possibly do it with another tox extension that complements tox-uv instead of replacing it?
I'm not up to date on tox's plans for python discovery, maybe there's another way to hook into it.

## Additional context

Uv python toolchain docs https://docs.astral.sh/uv/concepts/python-versions/ (NOTE: preview docs for preview features)

**Comment by bluss** [comment]
Well ok, my bad, that's what it's already doing, great.

**Comment by codl** [comment]
This doesn't seem to work for python versions that uv could provide but that don't already exist on the system, tox skips them, or if `skip_missing_interpreters` is false tox fails with "No interpreter found for Python X.Y in managed installations or system path"
