### ISSUE TITLE
Make uv dependency optional

### ISSUE THREAD

**Issue by RomainBrault** [tox-dev/tox-uv#82]
## What's the problem this feature will solve?

Currently uv is installed in tox's virtualenv.

If a user have its own uv in another virutalenv, it might cause confusion and more management (e.g. updates)

## Describe the solution you'd like

Follow PyPA's build implementation:

https://github.com/pypa/build/blob/main/src/build/env.py

```python
        try:
            import uv

            self._uv_bin = uv.find_uv_bin()
        except (ModuleNotFoundError, FileNotFoundError):
            uv_bin = shutil.which('uv')
            if uv_bin is None:
                msg = 'uv executable not found'
                raise RuntimeError(msg) from None

            _ctx.log(f'Using external uv from {uv_bin}')
            self._uv_bin = uv_bin
```

In tox uv we could modify in https://github.com/tox-dev/tox-uv/blob/main/src/tox_uv/_venv.py:

```python
    @property
    def uv(self) -> str:
        return find_uv_bin()
```

by

```python
    @property
    def uv(self) -> str:
        try:
            import uv

            return uv.find_uv_bin()
        except (ModuleNotFoundError, FileNotFoundError):
            uv_bin = shutil.which('uv')
            if uv_bin is None:
                msg = 'uv executable not found'
                raise RuntimeError(msg) from None

        return uv_bin
 
        
```

Remove the toplevel import and make the dependency optional in pyproject.toml

## Additional context

To me the difficult part here is the test / coverage. I don't really know how to do.

It will also require to add some documentation, e.g.

By default tox-uv doesn't ship with uv. If you don´t have uv installed on your system, you can either
 1) Let tox-uv managed uv with `pip install tox-uv[uv`
 2) Install uv <link to uv install procedure here>

The drawback I'm seeing is that it might break systems where people didn't have uv install as a global tool and used only uv through tox-uv.

## Alternative Solutions

Do not make the uv dependency optional but prioritize system uv over tox-uv's uv.

```python
    @property
    def uv(self) -> str:
         uv_bin = shutil.which('uv')
         if uv_bin is None:
             return uv.find_uv_bin()

         return uv_bin        
```

**Comment by RomainBrault** [comment]
also a @cached_property instead of @property might be relevant.

**Comment by gaborbernat** [comment]
I am strongly against this. The sane behavior is to manage our version of UV; otherwise we have no idea whether what we get it compatible or not with the functionality we want to provide.

**Comment by razy69** [comment]
Hello,

It could be great to have an option for it. eg: manage_uv_version (bool)

Use case:

I use a tool version manager, like asdf.
In my repo, i pin the version of uv i want, eg: 0.5.4.

I have a Makefile which wrap my commands.

Make setup -> asdf install uv version specified in '.tool-versions' file, then create a venv using system uv, source it and install tox + tox-uv
Make tests -> source venv and execute tox -e tests, which create a tox env, install tests dependencies using uv and run them

I'm already ensuring compatibility of uv/tox-uv using asdf '.tool-versions' and i would like to avoid extra uv installation.

Thanks.

**Comment by MatteoGisondi** [comment]
Allowing opt-in behavior does trump the ensure compatibility argument, and makes the tool more flexible.

**Comment by gaborbernat** [comment]
If someones opts in and then fails to ensure compatbility and reports an error who will need to troubleshoot the issue? I am pretty sure the answer is me.

**Comment by gaborbernat** [comment]
Therefore, I will accept such PRs only if the contributor signs up to be maintainer too.

**Comment by razy69** [comment]
What if the documentation of this option says "Enable it at your own risk, no troubleshoot requests will be accepted" ?

**Comment by gaborbernat** [comment]
In my experience people are bad at reading disclaimers and documentation. They will likely still open the issue and then I will have to point out that we do not support this which is still effort on my side. Hence why requiring if we had this feature someone to become maintainer.
